#!/bin/bash
UKEX_SERVER_ROOT="/usr/local/UkexServer"
OPENLIB_DEST_DIR=$UKEX_SERVER_ROOT"/lib/"
OPENLIB_SRC_DIR=$(pwd)

export OPENLIB_DEST_DIR
export OPENLIB_SRC_DIR

mkdir $OPENLIB_DEST_DIR

if [ ! -d $OPENLIB_DEST_DIR  ];then
  echo "-----------------------------"
  echo "Create [" $OPENLIB_DEST_DIR "] Failed."
  echo "Run: mkdir " $UKEX_SERVER_ROOT "; chmod 777 " $UKEX_SERVER_ROOT
  echo "-----------------------------"
  exit
fi

#rm -rf $OPENLIB_DEST_DIR
#mkdir $OPENLIB_DEST_DIR

./build_jsoncpp
./build_openssl
./build_protobuf
./build_spdlog
./build_libuv
./build_http_parser

cd $OPENLIB_DEST_DIR
ln -s /usr/include/mysql mysqlinc
ln -s /usr/lib/mysql mysqllib

