// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukex.response.proto

#ifndef PROTOBUF_ukex_2eresponse_2eproto__INCLUDED
#define PROTOBUF_ukex_2eresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ukex {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ukex_2eresponse_2eproto();
void protobuf_AssignDesc_ukex_2eresponse_2eproto();
void protobuf_ShutdownFile_ukex_2eresponse_2eproto();

class response;

enum response_CONST {
  response_CONST_CMD = 111
};
bool response_CONST_IsValid(int value);
const response_CONST response_CONST_CONST_MIN = response_CONST_CMD;
const response_CONST response_CONST_CONST_MAX = response_CONST_CMD;
const int response_CONST_CONST_ARRAYSIZE = response_CONST_CONST_MAX + 1;

const ::google::protobuf::EnumDescriptor* response_CONST_descriptor();
inline const ::std::string& response_CONST_Name(response_CONST value) {
  return ::google::protobuf::internal::NameOfEnum(
    response_CONST_descriptor(), value);
}
inline bool response_CONST_Parse(
    const ::std::string& name, response_CONST* value) {
  return ::google::protobuf::internal::ParseNamedEnum<response_CONST>(
    response_CONST_descriptor(), name, value);
}
// ===================================================================

class response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ukex.response) */ {
 public:
  response();
  virtual ~response();

  response(const response& from);

  inline response& operator=(const response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const response& default_instance();

  void Swap(response* other);

  // implements Message ----------------------------------------------

  inline response* New() const { return New(NULL); }

  response* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const response& from);
  void MergeFrom(const response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef response_CONST CONST;
  static const CONST CMD =
    response_CONST_CMD;
  static inline bool CONST_IsValid(int value) {
    return response_CONST_IsValid(value);
  }
  static const CONST CONST_MIN =
    response_CONST_CONST_MIN;
  static const CONST CONST_MAX =
    response_CONST_CONST_MAX;
  static const int CONST_ARRAYSIZE =
    response_CONST_CONST_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CONST_descriptor() {
    return response_CONST_descriptor();
  }
  static inline const ::std::string& CONST_Name(CONST value) {
    return response_CONST_Name(value);
  }
  static inline bool CONST_Parse(const ::std::string& name,
      CONST* value) {
    return response_CONST_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // required string data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional string token = 3;
  bool has_token() const;
  void clear_token();
  static const int kTokenFieldNumber = 3;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // @@protoc_insertion_point(class_scope:ukex.response)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_token();
  inline void clear_has_token();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_ukex_2eresponse_2eproto();
  friend void protobuf_AssignDesc_ukex_2eresponse_2eproto();
  friend void protobuf_ShutdownFile_ukex_2eresponse_2eproto();

  void InitAsDefaultInstance();
  static response* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// response

// required int32 status = 1;
inline bool response::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void response::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void response::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void response::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 response::status() const {
  // @@protoc_insertion_point(field_get:ukex.response.status)
  return status_;
}
inline void response::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:ukex.response.status)
}

// required string data = 2;
inline bool response::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void response::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void response::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void response::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& response::data() const {
  // @@protoc_insertion_point(field_get:ukex.response.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void response::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ukex.response.data)
}
inline void response::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ukex.response.data)
}
inline void response::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ukex.response.data)
}
inline ::std::string* response::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:ukex.response.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* response::release_data() {
  // @@protoc_insertion_point(field_release:ukex.response.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void response::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:ukex.response.data)
}

// optional string token = 3;
inline bool response::has_token() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void response::set_has_token() {
  _has_bits_[0] |= 0x00000004u;
}
inline void response::clear_has_token() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void response::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_token();
}
inline const ::std::string& response::token() const {
  // @@protoc_insertion_point(field_get:ukex.response.token)
  return token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void response::set_token(const ::std::string& value) {
  set_has_token();
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ukex.response.token)
}
inline void response::set_token(const char* value) {
  set_has_token();
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ukex.response.token)
}
inline void response::set_token(const char* value, size_t size) {
  set_has_token();
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ukex.response.token)
}
inline ::std::string* response::mutable_token() {
  set_has_token();
  // @@protoc_insertion_point(field_mutable:ukex.response.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* response::release_token() {
  // @@protoc_insertion_point(field_release:ukex.response.token)
  clear_has_token();
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void response::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    set_has_token();
  } else {
    clear_has_token();
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:ukex.response.token)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ukex

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ukex::response_CONST> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ukex::response_CONST>() {
  return ::ukex::response_CONST_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ukex_2eresponse_2eproto__INCLUDED
